web-shop-develop/catalog/urls.py
from django.urls import path
from catalog.apps import CatalogConfig
from catalog.views import contacts, HomeListView, ProductDetailView, ProductCreateView, BlogCreateView, BlogUpdateView, \
    BlogListView, BlogDetailView, BlogDeleteView

app_name = CatalogConfig.name

urlpatterns = [
    path('', HomeListView.as_view(), name='homepage'),
    path('contacts/', contacts, name='contacts'),
    path('product/<int:pk>/', ProductDetailView.as_view(), name='product_details'),
    path('product_create/', ProductCreateView.as_view(), name='product_create'),
    path('blog_create/', BlogCreateView.as_view(), name='blog_create'),
    path('blog_update/<int:pk>/', BlogUpdateView.as_view(), name='blog_update'),
    path('blogs/', BlogListView.as_view(), name='blogs'),
    path('blog_details/<int:pk>/', BlogDetailView.as_view(), name='blog_details'),
    path('blog_delete/<int:pk>/', BlogDeleteView.as_view(), name='blog_delete'),
]

web-shop-develop/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web-shop-develop/catalog/models.py
import datetime
from django.utils import timezone
from django.db import models

NULLABLE = {'blank': True, 'null': True}


# Create your models here.

class Category(models.Model):
    category_name = models.CharField(max_length=100, verbose_name='категория')
    category_description = models.TextField(verbose_name='описание', **NULLABLE)

    def __str__(self):
        return f'{self.category_name}'

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'


class Product(models.Model):
    product_name = models.CharField(max_length=100, verbose_name='название товара')
    product_description = models.TextField(verbose_name='описание', **NULLABLE)
    product_image = models.ImageField(verbose_name='изображение', upload_to='product/', **NULLABLE)
    product_category = models.ForeignKey(Category, to_field='id', default=None, on_delete=models.deletion.CASCADE, verbose_name='категория')
    product_price = models.FloatField(verbose_name='цена за покупку')
    date_of_creation = models.DateField(verbose_name='дата создания', default=timezone.now)
    date_of_last_change = models.DateField(verbose_name='дата последнего изменения', default=timezone.now)

    def __str__(self):
        return f'{self.product_name}'

    class Meta:
        verbose_name = 'товар'
        verbose_name_plural = 'товары'


class Blog(models.Model):

    title = models.CharField(max_length=100, verbose_name='заголовок')
    slug = models.CharField(max_length=50, unique=True, verbose_name='slug')
    body = models.TextField(verbose_name='содержимое')
    image = models.ImageField(upload_to='blogs/', verbose_name='изображение', **NULLABLE)
    created_at = models.DateField(default=timezone.now, verbose_name='дата создания')
    is_published = models.BooleanField(default=True, verbose_name='опубликован')
    views_count = models.IntegerField(default=0, verbose_name='количество просмотров')

    def __str__(self):
        return f"{self.title}"

    class Meta:
        verbose_name = 'блог'
        verbose_name_plural = 'блоги'

web-shop-develop/catalog/views.py
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, DeleteView, CreateView, UpdateView
from pytils.translit import slugify

from catalog.models import Product, Blog


# Create your views here.
class HomeListView(ListView):
    model = Product
    extra_context = {'title': 'SkyStore Главная'}


class ProductDetailView(DetailView):
    model = Product
    extra_context = {'title': 'Информация о товаре'}


class ProductCreateView(CreateView):
    model = Product
    fields = ('product_name', 'product_description', 'product_category', 'product_price', 'product_image')
    success_url = reverse_lazy('catalog:homepage')


def contacts(request):
    context = {'title': 'SkyStore Контакты'}
    return render(request, 'catalog/contacts.html', context)


class BlogCreateView(CreateView):
    model = Blog
    fields = ('title', 'body', 'image', 'is_published', 'views_count')
    success_url = reverse_lazy('catalog:blogs')

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.title)
            new_mat.save()

        return super().form_valid(form)


class BlogListView(ListView):
    model = Blog
    extra_context = {'title': 'Блоги'}

    def get_queryset(self, *args, **kwargs):
        query = super().get_queryset(*args, **kwargs)
        query = query.filter(is_published=True)

        return query


class BlogDetailView(DetailView):
    model = Blog
    extra_context = {'title': 'Блог'}

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()

        return self.object


class BlogUpdateView(UpdateView):
    model = Blog
    fields = ('title', 'body', 'image', 'is_published', 'views_count')
    success_url = reverse_lazy('catalog:blogs')

    def get_success_url(self):
        return reverse('catalog:blog_details', args=[self.object.pk])


class BlogDeleteView(DeleteView):
    model = Blog
    success_url = reverse_lazy('catalog:blogs')

web-shop-develop/catalog/templates/catalog/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ title }}</title>
    <link href="/static/catalog/css/bootstrap.min.css" rel="stylesheet" type="text/css">
</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Skystore</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:blogs' %}">Блоги</a>
        <a class="p-2 btn btn-outline-primary" href="/">Каталог</a>
        <a class="p-2 btn btn-outline-primary" href="/contacts/">Контакты</a>
    </nav>
</div>



<div class="container">
    {% block content %}
    {% endblock %}
    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                SkyStore
                <small class="d-block mb-3 text-muted">&copy; 2023</small>
            </div>
            <div class="col-6 col-md text-right">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small ">
                    <li><a class="text-muted" href="{% url 'catalog:blogs' %}">Блоги</a></li>
                    <li><a class="text-muted" href="/">Каталог</a></li>
                    <li><a class="text-muted" href="/contacts/">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>

<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

web-shop-develop/catalog/templates/catalog/blog_confirm_delete.html
{% extends 'catalog/base.html' %}
{% block content %}
    <div class="row">
        <div class="col-4">
            <div class="card">
                <div class="card-header text-center">
                    <h2>Удаление блога</h2>
                </div>
                <div class="card-body">
                    <div class="col-12">
                        <h5>Вы уверены, что хотите удалить блог {{ object.title }}?</h5>
                        <div class="6">
                        </div>
                        <div class="6">
                            <form method="post">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-danger">Удалить</button>
                                <a href="{% url 'catalog:blogs' %}" class="btn btn-secondary">Отменить</a>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

web-shop-develop/catalog/templates/catalog/blog_detail.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
    <div class="row">
        <div class="col-10">
            <a href="{% url 'catalog:blogs' %}">Вернуться к блогам</a>
            <h3>{{ object.title }}</h3>
        </div>
        <div class="col-2 text-right">
            <a href="{% url 'catalog:blog_update' object.pk %}">Редактировать блог</a>
        </div>
    </div>
    <div class="row">
        <div class="col-6">
            <p>{{ object.body }}</p>
            <div class="footer text-muted">
                <small>Количество просмотров: {{ object.views_count }}</small>
                <div class="col-3">
                    <a class="text-danger" href="{% url 'catalog:blog_delete' object.pk %}">Удалить блог</a>
                </div>
            </div>
        </div>
        <div class="col-6">
            <img src="{{ object.image|mymedia }}" alt="Картинка блога" width="100%">
        </div>
    </div>
{% endblock %}

web-shop-develop/catalog/templates/catalog/blog_form.html
{% extends 'catalog/base.html' %}
{% block content %}
    <div class="col">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.as_p }}
                            {% if object %}
                                <button type="submit" class="btn btn-success">Принять изменения</button>
                            {% else %}
                                <button type="submit" class="btn btn-success">Добавить блог</button>
                            {% endif %}
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

web-shop-develop/catalog/templates/catalog/blog_list.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
    <header class="text-center"><h2>Блоги Skystore</h2></header>
    <div class="row">
        <div class="col-12 text-center">
            <a href="{% url 'catalog:blog_create' %}" class="btn btn-lg btn-success w-25 mt-4">Создать блог</a>
        </div>
        {% for object in object_list %}
            <div class="col-6 pt-3">
                <div class="card h-100">
                    <div class="card-body">
                        <div class="card-header text-center m-2">
                            <h4>{{ object.title }}</h4>
                        </div>
                        <div class="card-img text-center">
                            <img src="{{ object.image|mymedia }}" alt="Изображение блога" width="100%">
                        </div>
                    </div>

                    <div class="card-footer">
                        <div class="row mt-3">
                            <div class="col-8">
                                <a href="{% url 'catalog:blog_details' object.pk %}"
                                   class="btn form-control btn-primary">Читать
                                    подробнее</a>
                            </div>
                            <div class="col-4">
                                <small class="d-block mr-3  text-right text-muted">количество
                                    просмотров: {{ object.views_count }}</small>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

web-shop-develop/catalog/templates/catalog/contacts.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="row text-start">
    <div class="col-lg-9 col-md-6 col-sm-12">
        <div class="card mb-4 box-shadow">
            <div class="card-body">
                <table class="table table-striped">
                    <tr>
                        <td class="w-25">Страна</td>
                        <td>USA</td>
                    </tr>
                    <tr>
                        <td class="w-25">ИНН</td>
                        <td>91-1144442</td>
                    </tr>
                    <tr>
                        <td class="w-25">Адрес</td>
                        <td>Redmond,WA,98052-6399</td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
    <div class="col-lg-3 col-md-6 col-sm-12">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
            </div>
            <div class="card-body">
                <form method="post" action="" class="form-floating">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="name">Имя</label>
                        <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                    </div>
                    <div class="mb-3">
                        <label for="phone">Телефон</label>
                        <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон"
                               required>
                    </div>
                    <div class="mb-3">
                        <label for="message">Сообщение</label>
                        <textarea name="message" class="form-control" id="message" placeholder="Контактный телефон"
                                  required></textarea>
                    </div>
                </form>
                <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
            </div>
        </div>
    </div>
</div>
{% endblock %}

web-shop-develop/catalog/templates/catalog/includes/inc_product.html
<div class="col-3">
    <div class="card mb-4 box-shadow">
        <div class="card-header">
            <h4 class="my-0 font-weight-normal">{{ object.product_name }}</h4>
        </div>
        <div class="card-body">
            <h1 class="card-title pricing-card-title">$ {{ object.product_price }}</h1>
            <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                {% if object.product_description|length > 100 %}
                    {{ object.product_description|slice:":100" }}...
                {% else %}
                    {{ object.product_description|slice:":100" }}
                {% endif %}
            </ul>
            <a href="{% url 'catalog:product_details' object.pk %}" type="button"
               class="btn btn-lg btn-block btn-outline-primary">К товару</a>
        </div>
    </div>
</div>

web-shop-develop/catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-4">
                <h6>{{ object.product_category.category_name|title }}</h6>
            </div>
        </div>
        <div class="row">
            <div class="col-4">
                <h1>{{ object.product_name|title }}</h1>
            </div>
        </div>
        <div class="row">
            <div class="col-1">
            </div>
            <div class="col-4">
                <div class="card-img-top">
                    <img src="{{ object.product_image|mymedia }}" alt="Фотография товара" width=" 125%" height=" 90%">
                </div>
            </div>
            <div class="col-2">
            </div>
            <div class="col-5">
                <div class="card" style="width: 18rem;">
                    <h2 class="card-title text-center mt-4 pricing-card-title">
                        Цена: {{ object.product_price }} руб.
                    </h2>
                    <hr>
                    <div class="card-body">
                        <p class="card-text">{{ object.product_description }}</p>

                        <button type="button" class="w-100 btn btn-lg btn-success">Купить</button>
                    </div>
                </div>
            </div>
        </div>


    </div>
{% endblock %}

web-shop-develop/catalog/templates/catalog/product_form.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="col">
<div class="row">
    <div class="col-6">
        <div class="card">
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">Добавить</button>
                </form>
            </div>
        </div>
    </div>
</div>
</div>
{% endblock %}

web-shop-develop/catalog/templates/catalog/product_list.html
{% extends 'catalog/base.html' %}
{% block content %}
    <div class="row text-center">
        <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
            <h1 class="display-4">Skystore</h1>
            <p class="lead">Skystore - это отличный вариант хранения ваших плагинов и примеров кода, который вы бы
                хотели продать</p>
        </div>
    </div>
    <div class="row text-right ">
        <div class="col-12 md-4">
            <a href="{% url 'catalog:product_create' %}" type="button" class="btn btn-success mb-4">Добавить товар</a>
        </div>
    </div>
    <div class="row text-center">
        {% for object in object_list %}
            {% include 'catalog/includes/inc_product.html' %}
        {% endfor %}
    </div>
{% endblock %}